version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///shipping_quote.db
      - SECRET_KEY=dev_key_for_testing
      - JWT_SECRET_KEY=jwt_secret_key
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=shipping_quote_password
      - POSTGRES_USER=shipping_quote_user
      - POSTGRES_DB=shipping_quote_db
    restart: always

volumes:
  postgres_data:
